Check the PR name

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -8,6 +8,28 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  validate-title:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out PR
+        uses: actions/checkout@v4.2.2
+      - name: Validate PR title
+        env:
+          PR_TITLE: ${{ github.event.pull_request.title }}
+        run: |
+          echo "Validating PR title: \"$PR_TITLE\""
+
+          REGEX='^\[?(WIP|wip)?\]?\s*(DEMRUM-[0-9]+(,\s?DEMRUM-[0-9]+)*|NO-TICKET):\s.+$'
+
+          if [[ "$PR_TITLE" =~ $REGEX ]]; then
+            echo "✅ PR title is valid."
+          else
+            echo "❌ PR title is invalid."
+            echo "It must match the format: DEMRUM-1234: Description"
+            echo "Or: DEMRUM-1234, DEMRUM-5678: Description"
+            echo "Or: NO-TICKET: Description"
+            exit 1
+          fi
   build:
     runs-on: ubuntu-24.04
     steps:
@@ -17,7 +39,6 @@ jobs:
         with:
           distribution: temurin
           java-version: 17
-
       - name: Build and test
         run: touch ./local.properties; ./gradlew check javadoc assemble
       - name: Upload coverage to Codecov
@@ -31,7 +52,6 @@ jobs:
         with:
           distribution: temurin
           java-version: 17
-
       - name: Run ktlint
         run: ./gradlew ktlintCheck
   check_links:
